export const ACTIONS = {
  ADD_PHRASE: "ADD_PHRASES",
  ADD_SPOTTING_PHRASE: "ADD_SPOTTING_PHRASE",
  REMOVE_SPOTTING_PHRASE: "REMOVE_SPOTTING_PHRASE",
  UPDATE_SPOTTING_PHRASE: "UPDATE_SPOTTING_PHRASE"
};
