export const ACTIONS = {
  UPDATE_CONNECTION_STATUS: "UPDATE_CONNECTION_STATUS",
  CONNECTION_START: "CONNECTION_START",
  CONNECTION_STOP: "CONNECTION_STOP",
  ADD_PHRASE: "ADD_PHRASES",
  ADD_SPOTTING_PHRASE: "ADD_SPOTTING_PHRASE",
  REMOVE_SPOTTING_PHRASE: "REMOVE_SPOTTING_PHRASE",
  UPDATE_SPOTTING_PHRASE: "UPDATE_SPOTTING_PHRASE"
};
